/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'dell-pc' at '17-5-8 下午2:20' with Gradle 2.11
 *
 * @author dell-pc, @date 17-5-8 下午2:20
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
